title: Johnny Ferreira
description: Dicas sobre Linux, Cloud, DevOps e outras paradas.
theme: just-the-docs

url: https://johnnyfsan.github.io/site/

aux_links:
  Template Repository: https://github.com/just-the-docs/just-the-docs-template
