title: "TI da Hora!"
email: johnny.ferreira.santos@gmail.com
timezone: UTC-3
baseurl: "https://tidahora.com.br"
permalink: "/:title/"
logo: 'assets/images/logo.png'
favicon: 'assets/images/favicon.ico'
author: Johnny Ferreira
paginate: 30
disqus: 'tidahora'
locale: pt_BR
lang: pt_BR
feed_items: 10
feed_update_period: daily
feed_update_frequency: 1
markdown: kramdown
highlighter: rouge
kramdown:
  input: GFM
  syntax_highlighter_opts:
    disable: false
sass:
  sass_dir: _sass
  style: :compressed
ganalytics: G-Q7Z612VPL5

# The keywords to associate with your website, for SEO purposes
keywords: "linux, devops, cloud, tecnologia, infraestrutura, docker, aws, amazon web services, terraform, gcp, google cloud platform"

# Authors
authors:
  Johnny:
    name: Johnny Ferreira
    display_name: Johnny Ferreira
    avatar: 'assets/images/sal.png'
    email: johnny.ferreira.santos@gmail.com
    description: "Apenas um cara da TI"

# Social
social:
  instagram: https://www.instagram.com/johnnyfsan
  facebook: https://www.facebook.com/johnnyferrreirasantos
  linkedin: https://www.linkedin.com/in/johnnyferreiradossantos/

# Plugins
plugins: 
- jekyll-paginate
- jekyll-sitemap
- jekyll-feed
- jekyll-seo-tag
- jekyll-archives
